language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t ganiths/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true ganiths/docker-react npm run test
